### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by hecperleo** [gKouros/path-smoothing-ros#1]
Hello! Can you explain how to start using this repository? I downloaded it and was able to make a catkin_make without errors, but I can't run demo.launch properly. I get the following messages that I don't know how to interpret: 

```
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 307, in main
    p.start()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self._start_infrastructure()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 217, in _start_infrastructure
    self._load_config()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 132, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/config.py", line 451, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 746, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 718, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 652, in _recurse_load
    default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 682, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 587, in _include_tag
    inc_filename = self.resolve_args(tag.attributes['file'].value, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 183, in resolve_args
    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 370, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 383, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 151, in _find
    source_path_to_packages=source_path_to_packages)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 197, in _find_executable
    full_path = _get_executable_path(rp.get_path(args[0]), path)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 203, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
ResourceNotFound: path_smoothing_ros
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/user/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share

```
I'm in trouble right now and your project would be a big help, 

Thank you!

**Comment by gkouros** [comment]
Hello,

First of all make sure that your workspace is sourced 
$ source path_to_catkin_ws/devel/setup.bash

You can also try to launch the demo directly from the package path.
$ cd path_to_package/path-smoothing-ros/launch & roslaunch demo.launch

Hope that helps.

Regards,
George

**Comment by hecperleo** [comment]
Thank you for responding quickly, it's appreciated. 

It's working, I made a mistake. Is it possible to pass a nav_msgs:: Path (which is published) through your algorithm and return another nav_msgs:: Path? Instead of using path.yaml

I'm trying to learn by reading your demo.cpp

Thank you again!

**Comment by gkouros** [comment]
Yes, it's possible. You can modify the demo or write a new node that listens to a nav_msgs::Path message
and performs the smoothing. Then you can publish the new smoothed path.

**Comment by vish2701** [comment]
I also get the same error as above. It worked the first time but since then I am not able to launch the demo.launch file. Any help would be appreciated.

**Comment by vish2701** [comment]
Hello, i am also facing the same problem as above and can't resolve it with the solution given above. I have sourced the file correctly but am still not able to run the launch file. Please help

**Comment by gkouros** [comment]
Can you send me your console output?

**Comment by vish2701** [comment]
Hello,

Thankyou for your response. I am trying to write a different algorithm
because I didn't quite understand your method. Can you explain it to me if
possible as to how the code works? It'd be of great help.

Also, the repository functions properly. Sorry for the issue post. I am
just picking up ROS at the moment and so the errors from my end.

It'd be great help if you could explain the code to me.

Regards
Vishwas Iyer

**Comment by gkouros** [comment]
Have a look at this paper. It explains a big part of the algorithm.
https://ieeexplore.ieee.org/document/1225546

**Comment by vish2701** [comment]
Thankyou so much!

Regards
Vishwas Iyer

**Comment by gkouros** [comment]
I provided you with the wrong paper on the link above. I have corrected the link with the actual paper, so have a look again. The paper is also listed in the README of the repository.
Regards,
George

**Comment by vish2701** [comment]
Thanks a lot!

Regards
Vishwas Iyer
